### ISSUE TITLE
Is this wrong?

### ISSUE THREAD

**Issue by MNegus** [deanott/CatDiscordBot#4] opened 2017-08-08 10:49 UTC
Idk what this is but delete it

**Comment by deanott** [comment] 2017-08-08 11:13
Does it run? Please send a issue and the bug report showing this does not work

**Comment by MNegus** [comment] 2017-08-08 11:15
Issue: Breaks the Geneva convention

**Comment by deanott** [comment] 2017-08-08 11:18
I believe this is a duplicate of #4, closing

**Closed** 2017-08-08 11:18 UTC
Labels: duplicate, enhancement
